# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [1]:
import numpy as np

In [2]:
# ejercicio 1
a = np.array([1, 2, 3, 4])
0 in a

False

In [6]:
# ejercicio 2
a = np.array([0, 0, 2, 0])
np.any(a != 0)

np.True_

In [8]:
# ejercicio 3
a = np.array([1, 2, np.nan, np.inf])
np.any(np.isnan(a) | np.isinf(a))

np.True_

In [9]:
# ejercicio 4
a = np.array([1, 2, np.inf])
np.any(np.isinf(a))

np.True_

In [10]:
# ejercicio 5
a = np.array([1, np.nan, 3])
np.any(np.isnan(a))

np.True_

In [11]:
# ejercicio 6
a = np.array([1, 3, 5])
b = np.array([2, 3, 4])

mayor = a > b
mayor_igual = a >= b
menor = a < b
menor_igual = a <= b

print("a > b :", mayor)
print("a >= b :", mayor_igual)
print("a < b :", menor)
print("a <= b :", menor_igual)

a > b : [False False  True]
a >= b : [False  True  True]
a < b : [ True False False]
a <= b : [ True  True False]


In [13]:
# ejercicio 7

a = np.array([1, 7, 13, 105])
a.nbytes

32

In [15]:
# ejercicio 8

ceros = np.zeros(10)
unos = np.ones(10)
cincos = np.full(10,5)

print(ceros)
print(unos)
print(cincos)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]


In [16]:
# ejercicio 9

a = np.arange(30, 71)
a

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [17]:
# ejercicio 10

a = np.arange(30, 71, 2)
a

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [18]:
# ejercicio 11

identidad = np.eye(3)
identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# ejercicio 12

numero = np.random.rand()
numero

0.6551866884413368

In [30]:
# ejercicio 13

a = np.random.rand(15)
a

array([0.95377838, 0.57025406, 0.18757023, 0.19013598, 0.75422001,
       0.73635176, 0.9592531 , 0.01871808, 0.77155365, 0.0235188 ,
       0.06100284, 0.27777311, 0.28169655, 0.65732832, 0.38360114])

In [31]:
# ejercicio 14

a = np.arange(15, 56)
a[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [35]:
# ejercicio 15

v=np.arange(5,51,5)
v

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
# ejercicio 16

v = np.arange(21)
v[9:16] *= -1

v

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

In [36]:
# ejercicio 17

a = np.array([1, 2, 3])

lista = a.tolist()
lista

[1, 2, 3]

In [37]:
# ejercicio 18

l = [1, 2, 3]

a = np.array(l)
a

array([1, 2, 3])

In [39]:
# ejercicio 19
m = np.array([[1,2],[3,4]])

pares = (m % 2 ==0)
pares

array([[False,  True],
       [False,  True]])

In [40]:
# ejercicio 20
m = np.array([[1, 2, 3],
              [4, 5, 6]])

filas, columnas = m.shape

print("Filas:", filas)
print("Columnas:", columnas)

Filas: 2
Columnas: 3
